version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: wikifeed-redis
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"

  feed-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PORT: ${HTTP_PORT:-8080}
    container_name: wikifeed-api
    depends_on:
      - redis
    volumes:
      - ./config/:/app/config/:ro
    environment:
      - REDIS_ADDR=redis:${REDIS_PORT:-6379}
    ports:
      - "${HTTP_PORT:-8080}:${HTTP_PORT:-8080}"