version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: wikifeed-redis
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"

  db:
    image: postgres:15-alpine
    container_name: wikifeed-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-appuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}
      - POSTGRES_DB=${POSTGRES_DB:-storydb}
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    volumes:
      - db_data:/var/lib/postgresql/data

  feed-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PORT: ${HTTP_PORT:-8080}
    container_name: wikifeed-api
    depends_on:
      - redis
      - db
    volumes:
      - ./config/:/app/config/:ro
    environment:
      - REDIS_ADDR=redis:${REDIS_PORT:-6379}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-appuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}
      - POSTGRES_DB=${POSTGRES_DB:-storydb}
    ports:
      - "${HTTP_PORT:-8080}:${HTTP_PORT:-8080}"

volumes:
  db_data: