auth:
  # Секретный ключ для подписи JWT access-токенов
  jwt_secret: "your-very-secret-key"

  # Время жизни access-токена (краткоживущий, например 15 минут)
  access_token_ttl: "15m"

  # Время жизни refresh-токена (долгоживущий, например 7 дней = 168 часов)
  refresh_token_ttl: "168h"