prefetcher:
  enabled: true            # Включён ли префетчер (можно отключить через конфиг без изменения кода)
  interval: 60s            # Как часто префетчер просыпается и проверяет количество фактов в Redis
  batch_size: 10           # Сколько фактов загружать за одну итерацию префетчера
  min_facts: 10           # Минимальное количество фактов, которое должно быть в Redis
  prefetch_on_start: true  # Нужно ли сразу подгружать факты при старте приложения
